# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  issue_comment:
  pull_request_target:
    branches: [ master]
env:
  PR_NUMBER: ${{ github.event.pull_request.number }}
  CommentString: ${{ github.event.comment.body }}
  EVENT_TYPE: ${{github.event.GITHUB_EVENT_NAME}}
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Display the path
        run: |
          echo "Event type: ${{env.EVENT_TYPE}}"
          if [ "$STR" == *"screenshot:"* ] || [ "$STR" == *"SCREENSHOT:"* ]; then
            echo "Started generating screenshots.."
          fi
        #shell: bash
      - name: Print PR Number
        run: |
          echo PRNumber1
          echo 1 ${{ github.event.issue.number }}
          echo PR Number3: ${{github.event.pull_request.number}}
          echo "PR number4 = ${{ env.PR_NUMBER }}"
          echo "PR number5 = ${{ github.event.pull_request.number }}"
          echo "Comment ${{env.CommentString}}"
          echo "event type1: ${{env.GITHUB_EVENT_NAME}}"
#       - name: upload to S3
#         uses: RandhirMSingh/S3Manager@main
#         with:
#           args: --acl public-read
#         env:
#           FILE:  "."
#           AWS_REGION: 'ap-south-1'
#           S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
#           S3_KEY: ${{ secrets.S3_KEY }}
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           REPO: ${{ github.repository }}
#           PR_NUMBER: ${{ github.event.issue.number }}
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     
